language: node_js
node_js: node
services: mongodb
deploy:
  provider: heroku
  api_key:
    secure: FEsno9huXXzNq7YWBuCmqiA1P3C0BayZAQTdGbOsmfzu1ze2GTJns/MedbiAyoZJiNMwXAwt64RMpKC40CZVAwGaAsRirHfMwSqTUUEe4ACqYqcrePB3qvTHO2dPmZbur6KPfq3PUO5wUWcxIVbPGCqUo8MSyiJ1YNTv9WrZ6PmF8uDguW/LYx2MlVHJkow2wXBlozweGVnoZVhxz6urP6/Xpk6QLLvTrbjbNGgLDlPcFPRby+xeXB9eV5SVogRTBYXQ7x4MWP0x4GfhHUTFN7T1kVhJgra4maL+wq0+DwOE2dGU7835R/8P501Or4HKrVWRc7B97IxEioOzq93IDVBf7vdAW0NFLNucEguUknpyDpWNcaDxb9weZQqHeqpxPKgPgGOXbyOeMlzWCfOthYFv0ppZ6AY64ktQ2Y80BITGEFVbaJYQSN7XZXv5JieT85/XhmrrtexhxiymvKk1XFQm/qdoI4MSyHp/KWpW4w35sebE4sUstq2/sWxtIQHtIXfM6YeiLi4l/2xrBz7RX3F7q4H21taU68dp6wgIyUnITQr8HLkHEbKfM2NUsHDERTdRoxngdsXf+qM17wIC5NlGgtQCsnyQBzBYR50HzfipnelBN4qnd9I/Zv2o5IrNDRF72W5IfhOidnVN5kn6Vw6Zx/oSlgNtMVeIXeBpeLc=
  app: dry-tor-47578
  on:
    repo: bdcrews/maintenance-logger
